name: 'Gmail Summary with OpenAI'
description: 'Summarize Gmail messages using OpenAI API'
author: 'Leo Fu'

inputs:
  service_account_key:
    description: 'Google Cloud service account key JSON string'
    required: true
  openai_api_key:
    description: 'OpenAI API key for generating summaries'
    required: true
  max_emails:
    description: 'Maximum number of emails to summarize'
    required: false
    default: '10'
  label:
    description: 'Gmail label to filter emails (optional)'
    required: false
    default: 'INBOX'
  days_ago:
    description: 'Number of days of emails to summarize'
    required: false
    default: '1'

outputs:
  summary:
    description: 'Generated summary of Gmail messages'
  processed_emails:
    description: 'Number of emails that were processed'
  error:
    description: 'Error message if any occurred during execution'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'mail'
  color: 'blue'
