name: 'Delay for a given number of milliseconds'
description: 'Delay for a given number of milliseconds'
author: 'Leo Fu'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'The number of milliseconds to wait'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'The time it took to wait for'

runs:
  using: node20
  main: dist/index.js
