name: 'PR Review Summary'
description: 'Summarizes all PRs pending your review using OpenAI'
author: 'Your Name'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
  openai_api_key:
    description: 'OpenAI API key'
    required: true
  model:
    description: 'OpenAI model to use'
    required: false
    default: 'gpt-4'
  max_prs:
    description: 'Maximum number of PRs to summarize'
    required: false
    default: '100'
  days_ago:
    description: 'Only include PRs created within this many days'
    required: false
    default: '1'

outputs:
  summary:
    description: 'JSON string containing all PR summaries'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'book-open'
  color: 'blue'
